# Generated by Django 4.2.29 on 2026-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('spirits', 'Spirits'), ('mixers', 'Mixers'), ('garnishes', 'Garnishes'), ('syrups', 'Syrups & Sweeteners'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
